mode: daemonset
image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

extraEnvs:
  - name: MACKEREL_APIKEY
    valueFrom:
      secretKeyRef:
        name: mackerel-arthur-1
        key: apikey
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: K8S_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

extraVolumes:
  - name: hostfs
    hostPath:
      path: /
extraVolumeMounts:
  - name: hostfs
    mountPath: /hostfs
    readOnly: true
    mountPropagation: HostToContainer

alternateConfig:
  receivers:
    hostmetrics:
      collection_interval: 1m
      root_path: /hostfs
      scrapers:
        cpu:
        disk:
        load:
        filesystem:
          exclude_fs_types:
            match_type: strict
            fs_types:
              - autofs
              - binfmt_misc
              - bpf
              - cgroup2
              - configfs
              - debugfs
              - devpts
              - devtmpfs
              - fusectl
              - hugetlbfs
              - iso9660
              - mqueue
              - nsfs
              - overlay
              - proc
              - procfs
              - pstore
              - rpc_pipefs
              - securityfs
              - selinuxfs
              - squashfs
              - sysfs
              - tracefs
          exclude_mount_points:
            match_type: regexp
            mount_points:
              - /dev/*
              - /proc/*
              - /sys/*
              - /run/k3s/containerd/*
              - /var/lib/docker/*
              - /var/lib/kubelet/*
              - /snap/*
        memory:
        network:

  processors:
    batch/metrics:
      send_batch_size: 5000
      send_batch_max_size: 5000
    resourcedetection:
      detectors: [env, k8snode]
    resource:
      attributes:
        - key: service.name
          value: worker-node
          action: upsert
        - key: service.namespace
          value: arthur-lke
          action: upsert

  exporters:
    otlp/mackerel:
      endpoint: otlp.mackerelio.com:4317
      compression: gzip
      headers:
        Mackerel-Api-Key: ${env:MACKEREL_APIKEY}

  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133

  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        receivers: [hostmetrics]
        processors: [batch/metrics, resourcedetection, resource]
        exporters: [otlp/mackerel]

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
